language: python

matrix:
  include:
  - python: 3.6
    env: TOXENV=pep8,pylint
  - python: 3.6
    env: TOXENV=docs

  - python: 3.4
    env: TOXENV=py34,codecov
  - python: 3.5
    env: TOXENV=py35,codecov
  - python: 3.6
    env: TOXENV=py36,codecov
  - python: 3.7-dev
    env: TOXENV=py37,codecov

  allow_failures:
  - env: TOXENV=py35,codecov
  - env: TOXENV=py37,codecov

install:
- pip install tox

script:
- tox -vvv

notifications:
  email: false