#cloud-config

hostname: tmldap

users:
  - name: vagrant
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDHq/KIUoKTgF3pvnqO+ClsQMXNql9bKPHAZAHssq8VozmEviND9xutDD8zsqvP3f4P3sQo8DNpqf+estOPuCUl6PrDJZG5R6r29X6RGt2/A0Wl9OgM0dgsxQiQ/nmQ9bM87Ve56UfF90X7k0Chh2z1VIXJ8vZLbwAd8oHNIbqynHLd2PeOozzWeAbBxv3A3IFtX5s+Ay9N1DhIuUNxNTyWOZMqJBhy4qt5fgQ/PxDPeIqGezNBnIZ6EOQZMRNPDkQGkyUbg9UE6AtLwnjJs35fAZxNyvvcJRT0ys5VR3xBcAvrbiZ+l60jSR0NRgbzLk9ngLvBB3fi+UIatKm1ru1M2cRk768Xkdo1AyYdnVuD9Cwb3n9exAqAo3bRTlM2YnNcT7zi9N2ts8XJ05PxnMmFfYy+Brn/i++wFUmxugEPGivBH74+vkwK4g7sAFoFyozr7TfAZtAKYyCRQ8WKGgDz/XDmIwSlAi/35JT1/cDUK0WsLbQQvyoiu6ZYclvyRxxN9NrnXrDVoQ+YNAXQrlauhAlPKEHZzbjx/wqGfKTJA5F0jedduCwMxYWOBuLbMBBLyU8S6gloK/ogU9ekOQGtPh+Tmr7m+2OMf+/OlZ+2l55PTrWTWrHULh9m/u0ZXdL04DEiOeTfh9jFIiAQaDc9pxttk5uDwQ1DdBai0u5vww== v.rautela01@gmail.com
    
packages:
  - openldap
  - openldap-clients 
  - openldap-servers